development:
  adapter: postgresql
  encoding: unicode
  database: openeducation_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: openeducation_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: openeducation_production
  pool: 5
